"""Add organization_id to users table

Revision ID: b0e238c1f1ed
Revises: d91b375d4880
Create Date: 2025-08-31 22:29:48.337538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0e238c1f1ed'
down_revision: Union[str, None] = 'd91b375d4880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jds', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('jds_user_id_fkey'), 'jds', type_='foreignkey')
    op.create_foreign_key(None, 'jds', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'organization_id')
    op.drop_constraint(None, 'jds', type_='foreignkey')
    op.create_foreign_key(op.f('jds_user_id_fkey'), 'jds', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('jds', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###