"""create initial schema from models

Revision ID: d91b375d4880
Revises: 
Create Date: 2025-08-18 14:56:31.757502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd91b375d4880'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.String(length=255), nullable=False),
    sa.Column('candidate_id', sa.String(length=512), nullable=False),
    sa.Column('ranking_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorites_candidate_id'), 'favorites', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_favorites_job_id'), 'favorites', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorites_job_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_candidate_id'), table_name='favorites')
    op.drop_table('favorites')
    # ### end Alembic commands ###
